# Generated by Django 4.0.3 on 2022-03-11 12:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjimayi_hol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
