# Generated by Django 4.0.3 on 2022-03-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_tarjimayi_hol'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
