# Generated by Django 3.2 on 2022-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devon', '0004_janrmisra_janrmisrasoz'),
    ]

    operations = [
        migrations.AddField(
            model_name='janrmisrasoz',
            name='mano',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
