# Generated by Django 3.2 on 2022-12-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devon', '0006_janrmisrasoz_auditoriya_yoshi'),
    ]

    operations = [
        migrations.AddField(
            model_name='janrmisra',
            name='janr_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
