# Generated by Django 3.2 on 2022-12-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devon', '0007_janrmisra_janr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='janrmisrasoz',
            name='janr_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
