# Generated by Django 4.0.3 on 2022-03-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ibora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayt', models.CharField(max_length=300)),
                ('ibora', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Maqol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misra', models.CharField(max_length=300)),
                ('maqol', models.CharField(max_length=300)),
            ],
        ),
    ]
