# Generated by Django 4.0.3 on 2022-03-11 12:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maqol_Ibora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibora',
            name='bayt',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maqol',
            name='misra',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
