# Generated by Django 4.0.3 on 2022-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talmeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayt', models.CharField(max_length=200)),
                ('mano', models.CharField(max_length=100)),
            ],
        ),
    ]
