# Generated by Django 4.0.3 on 2022-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sheriy_sanat', '0002_tazod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanosib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayt', models.CharField(max_length=300)),
                ('mano', models.CharField(max_length=300)),
            ],
        ),
    ]
