# Generated by Django 4.0.3 on 2022-03-11 12:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sheriy_sanat', '0003_tanosib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talmeh',
            name='bayt',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tanosib',
            name='bayt',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tazod',
            name='bayt',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
