# Generated by Django 4.0.3 on 2022-03-25 13:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sheriy_sanat', '0004_alter_talmeh_bayt_alter_tanosib_bayt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tashbeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayt', ckeditor.fields.RichTextField(blank=True)),
                ('mano', models.CharField(max_length=300)),
            ],
        ),
    ]
