# Generated by Django 4.0.4 on 2022-05-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sheriy_sanat', '0008_file_tanosib_file_tashbih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tashbeh',
            name='mano',
        ),
        migrations.AddField(
            model_name='tashbeh',
            name='oxshamish',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tashbeh',
            name='oxshatilmish',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tashbeh',
            name='sabab',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tashbeh',
            name='vosita',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
