# Generated by Django 4.0.3 on 2022-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazal', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='File',
        ),
        migrations.AddField(
            model_name='file',
            name='files',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
