# Generated by Django 4.0.3 on 2022-03-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='Files')),
            ],
        ),
    ]
