# Generated by Django 4.0.3 on 2022-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazal', '0003_remove_file_file_file_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
