# Generated by Django 4.0.3 on 2022-03-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gazal', '0007_file_talmeh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_Talmeh',
        ),
    ]
