# Generated by Django 4.0.4 on 2022-07-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazal', '0008_delete_file_talmeh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soz',
            name='soz',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
