# Generated by Django 3.2 on 2022-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gazal', '0009_alter_soz_soz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soz',
            name='soz',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
