# Generated by Django 3.2 on 2022-11-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gazal', '0010_alter_soz_soz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='misra',
            options={'verbose_name': 'Misra', 'verbose_name_plural': 'Misralar'},
        ),
        migrations.AlterModelOptions(
            name='soz',
            options={'verbose_name': 'Soz', 'verbose_name_plural': 'Sozlar'},
        ),
        migrations.AlterField(
            model_name='misra',
            name='gazal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misralar', to='Gazal.gazal'),
        ),
        migrations.AlterField(
            model_name='soz',
            name='soz_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Gazal.gazal', verbose_name='Gazal'),
        ),
    ]
